### ISSUE TITLE
References to PEM files should work when relative

### ISSUE THREAD

**Issue by genexp** [andrewchilds/overcast#27]
We really dig overcast, and we've started committing some of the files to our repositories so the ops related tools are alongside the code.  

Overcast doesn't seem to like complex file path for PEM files.  For instance, using $HOME doesn't work as expected.  The result is that currently team members must maintain their own clusters.json file.  It would be nice if we could support things like ~/.ssh and $HOME.

**Comment by andrewchilds** [comment]
This is available as of 0.6.4. Thanks!
