### ISSUE TITLE
SSHinception

### ISSUE THREAD

**Issue by genexp** [andrewchilds/overcast#29]
We recently disabled the option to ssh to multiple machines at one.  I think this was a good change, it was sorta confusing, and it's probably true that a script is a better approach.

However, it might be nice to allow multiple SSH if someone has csshX installed.  Its not a great tool, but it's pretty popular and available on both OSX & Linux.  Just a thought!

**Comment by andrewchilds** [comment]
This is available as of 0.6.4. Thanks!
