### ISSUE TITLE
On contributing to Overcast

### ISSUE THREAD

**Issue by garnold** [andrewchilds/overcast#34]
Hey @andrewchilds, I having a bit of trouble finding the right developer setup for contributing to Overcast.  Here's how I started:

1. Fork repo, clone locally
2. Prepend `/path/to/overcast/bin` to my `PATH`

With this setup, I'm getting an error when running `overcast run`: https://github.com/andrewchilds/overcast/issues/30

If skip updating my path, and run Overcast using `/path/to/overcast/bin/overcast`, it does pickup my local changes to the Overcast framework, however I have to include the path to my scripts, ie. `./bin/overcast run all scripts/my_script`.  Also, recipes do not pickup my local changes since they use the `overcast` from my classpath.

Finally, when creating recipes, in order for Overcast to find the scripts used by the recipe, I need to include the path to the script in the recipe, otherwise the script is not found.  Here's an example: https://github.com/andrewchilds/overcast/pull/31/files#diff-b481cea93210e4348dcd2edf85e892ecR19

Any help would be greatly appreciated.

**Comment by andrewchilds** [comment]
Hey @garnold, instead of messing with `$PATH` during development I just invoke `bin/overcast blah` - that way I can still quickly use or test against the npm-published version with `overcast blah`.

I should spell this out better in the README, and it's definitely worth renaming `bin/ssh` etc to avoid the collisions you're seeing. Will do. Thanks!

**Comment by garnold** [comment]
@andrewchilds Ah gotcha.  That will definitely work for testing scripts, but recipes will use `overcast` from NPM which won't include any changes to the framework.

**Comment by mafintosh** [comment]
Running `npm link` will add the local clone to your path
