### ISSUE TITLE
Problems configuring DigitalOcean access

### ISSUE THREAD

**Issue by limist** [andrewchilds/overcast#39]
The `.overcast/variables.json` file has two DigitalOcean keys, `DIGITALOCEAN_CLIENT_ID` and `DIGITALOCEAN_API_KEY`.  Are these compatible with the current DO API?   It's not clear what should go into the `_CLIENT_ID` value.  In any case, I keep seeing "Access Denied" messages. 

From the current DO control panel, https://cloud.digitalocean.com/settings/applications, one can now generate "Personal Access Tokens"   And I can verify that mine works when I do,
```sh
curl -H "Authorization: Bearer your-secret-DO-API-token" -X GET "https://api.digitalocean.com/v2/images?type=snapshot"
```

But using that access token in the overcast DIGITALOCEAN_CLIENT_ID or DIGITALOCEAN_API_KEY keeps resulting in the same "Access Denied" output with `overcast digitalocean x` commands.

Any help appreciated, thanks in advance!

**Comment by andrewchilds** [comment]
Yeah, Overcast is still not compatible with the latest version of the DO API. To generate v1 API keys, go to https://cloud.digitalocean.com/settings/applications, click "View API v1", and then click "Generate New Key".

Cheers!
Andrew

**Comment by limist** [comment]
@andrewchilds Thanks for the info; I don't see any text or link for "View API v1", maybe they deprecated it further than before?

**Comment by andrewchilds** [comment]
Hmm. It's on the top right for me:

![screenshot 2015-07-06 13 44 09](https://cloud.githubusercontent.com/assets/352089/8529267/d5c618a0-23e6-11e5-95c9-caa7b74c2cc4.png)

Try this URL? https://cloud.digitalocean.com/api_access

**Comment by limist** [comment]
Thanks, tried your link, it redirects to settings/billing with a message that Version 1 of the API is not compatible with Team Accounts; and I can't deactivate the Team without first deleting all droplets, which we're not able to do right now.  Any other ideas?  I'll also ask DO support...

**Comment by limist** [comment]
OK, DO can't help.  Any idea when overcast will support the v2 API?  :)

**Comment by andrewchilds** [comment]
I'm not sure when I'll be able to migrate Overcast over as it's not a trivial change, but I'll try to get to it in the next month or two since it's clear that some accounts can't access the old API... Thanks for letting me know!

**Comment by limist** [comment]
@andrewchilds  Thanks! FYI, support at DigitalOcean told me they're going to shut off the v1 API entirely, by November 1st, while continuing to push people off it in the meanwhile.  

They also mentioned this tool that they're working on, maybe the code here will help overcast: http://kbknapp.github.io/docli-rs/

**Comment by limist** [comment]
BTW, it may be worth warning people on the README, that are currently on DO v1 API: if you enable Team Account, you lose access to the v1 API.

**Comment by andrewchilds** [comment]
Hey @limist, just letting you know that Overcast now supports DigitalOcean API v2.

Cheers,
Andrew
