### ISSUE TITLE
Change Password on remote host

### ISSUE THREAD

**Issue by Acostan** [andrewchilds/overcast#43]
Hi,

I can't get this command to work 

"overcast run INSTANCE passwd"

the CLI asks for the pasword, but doesn't ask me to re-confirm the password

**Comment by andrewchilds** [comment]
Hello, `overcast run` is meant for running non-interactive commands on remote hosts. If you want to run an interactive command, you should use `overcast ssh [instance]` and run `passwd` once logged in.

**Comment by garnold** [comment]
@Acostan Non-interactive password change: https://snowulf.com/2012/02/16/non-interactive-unattended-password-change-under-ubuntu/

**Comment by Acostan** [comment]
Thanks!
